version: "3.9"

services:
  db:
    build:
      dockerfile: Dockerfile
      context: .
    image: postgres
    container_name: mysite_postgres
    volumes:
      - ~/.pg/pg_data/mysite:/var/lib/postgresql/data
    env_file:
      -  .env
  mysite_django:
    build:
      dockerfile: Dockerfile
      context: .
    image: mysite
    container_name: mysite_dj
    depends_on:
      - db
    env_file:
      - .env

