# Generated by Django 4.2.1 on 2024-03-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_cont',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
